import argparse
from content import get_video_metadata, get_meme_metadata
from generator import create_video
from telegram_bot import upload_to_telegram

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--category", default="fact", help="Video Category: fact or meme")
    args = parser.parse_args()
    
    print(f"🎬 TubeAutoma Starting in [{args.category.upper()}] mode...")
    
    # 1. Fetch Content
    if args.category == "meme":
        metadata = get_meme_metadata()
    else:
        metadata = get_video_metadata()
        
    print(f"Topic: {metadata['title']}")
    
    # 2. Generate Video
    # Get Pexels Key from Environment (Secrets)
    pexels_key = os.environ.get("PEXELS_API_KEY") 
    
    output_file = "viral_short.mp4"
    # Pass entire metadata object to generator now
    final_video_path = create_video(metadata, output_file, pexels_key)
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")
    
    video_path_final = final_video_path
    
    # 3. Upload to YouTube (Primary)
    youtube_id = None
    try:
        from youtube_uploader import upload_video
        youtube_id = upload_video(
            video_path_final, 
            metadata['title'], 
            metadata['description'], 
            metadata['tags']
        )
    except Exception as e:
        print(f"YouTube Upload Module Error: {e}")

    # 4. Delivery / Notification to Telegram
    bot_token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")
    
    if os.path.exists(final_video_path):
        caption = f"{metadata['title']}\n\n{metadata['tags']}\n\n🤖 Generated by TubeAutoma"
        if youtube_id:
            caption += f"\n\n✅ Uploaded to YouTube: https://youtu.be/{youtube_id}"
        else:
            caption += "\n\n⚠️ YouTube Upload Failed (Check Logs)"
            
        upload_to_telegram(final_video_path, caption, bot_token, chat_id)
        
        # Cleanup
        os.remove(final_video_path)
    else:
        print("Error: Video generation failed.")

if __name__ == "__main__":
    main()
