import argparse
import os
try:
    from content_enhanced import get_video_metadata, get_meme_metadata, get_long_video_metadata
except ImportError:
    get_video_metadata = None
    get_meme_metadata = None
    get_long_video_metadata = None
from content import get_curiosity_metadata
from generator import create_video
from thumbnail_generator import create_thumbnail
from telegram_bot import upload_to_telegram

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--category", default="fact", help="Video Category: fact, meme, long, or curiosity")
    args = parser.parse_args()
    
    print(f"[*] TubeAutoma Starting in [{args.category.upper()}] mode...")
    
    # 1. Fetch Content
    if args.category == "long":
        # Refinement 7: Long-form activation logic
        from datetime import datetime
        current_date = datetime.now()
        activation_date = datetime(2026, 1, 11)
        target_channel = os.environ.get("TARGET_CHANNEL")
        
        if target_channel == "curiosity" and current_date < activation_date:
            print(f"\n[BLOCKED] Long-form content for CurioByte is DISABLED until Jan 11, 2026.")
            print(f"Current Date: {current_date.strftime('%Y-%m-%d')}")
            return
            
        metadata = get_long_video_metadata()
    elif args.category == "meme":
        metadata = get_meme_metadata()
    elif args.category == "curiosity":
        metadata = get_curiosity_metadata()
    else:
        metadata = get_video_metadata()
        
    try:
        print(f"Topic: {metadata['title'].encode('cp1252', 'ignore').decode('cp1252')}")
    except:
        print(f"Topic: {metadata['title'].encode('ascii', 'ignore').decode('ascii')}")
    
    # 2. Generate Video
    # Get Pexels Key from Environment (Secrets)
    pexels_key = os.environ.get("PEXELS_API_KEY") 
    
    output_file = f"viral_{args.category}.mp4"
    # Pass entire metadata object to generator now
    final_video_path = create_video(metadata, output_file, pexels_key)
    
    # 2.1 Generate Thumbnail
    thumbnail_file = f"thumb_{args.category}.jpg"
    try:
        final_thumb_path = create_thumbnail(metadata['topic'], thumbnail_file, pexels_key)
    except Exception as e:
        print(f"Thumbnail Generation Failed: {e}")
        final_thumb_path = None
        
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")
    
    video_path_final = final_video_path
    
    # 3. Upload to YouTube (Primary)
    youtube_id = None
    try:
        from youtube_uploader import upload_video
        youtube_id = upload_video(
            video_path_final, 
            metadata['title'], 
            metadata['description'], 
            metadata['tags'],
            metadata.get('youtube_category', '27'),
            thumbnail_path=final_thumb_path,
            mode=metadata.get('mode', 'fact')
        )
    except Exception as e:
        print(f"YouTube Upload Module Error: {e}")

    # 4. Delivery / Notification to Telegram
    bot_token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")
    
    if os.path.exists(final_video_path):
        caption = f"{metadata['title']}\n\n{metadata['tags']}\n\n🤖 Generated by TubeAutoma"
        if youtube_id:
            caption += f"\n\n✅ Uploaded to YouTube: https://youtu.be/{youtube_id}"
        else:
            caption += "\n\n⚠️ YouTube Upload Failed (Check Logs)"
            
        upload_to_telegram(final_video_path, caption, bot_token, chat_id)
        
        # Cleanup
        os.remove(final_video_path)
        if final_thumb_path and os.path.exists(final_thumb_path):
            os.remove(final_thumb_path)
    else:
        print("Error: Video generation failed.")

if __name__ == "__main__":
    main()
